Html nri
Ryu-y-10/ryunosukeyoshimoto pull request #1
Opened 2020-04-14 06:58 UTC by Ryu-y-10

##  やったこと
- マークアップ
- HTMLチェッカー(エラー無し確認済み）

## やってないこと
- ハンバーガーメニューの実装
- レスポンシブ対応

2020-04-14 07:13 UTC, piasoratech requested changes
コメントしたので確認をお願いします！
タグの意味と文章構造に気を付けてマークアップしてみましょう。

2020-04-14 07:13 UTC, piasoratech commented on html-nri/index.html
> +                <h1 class="logo"><img src="nri-images/nri-logo.png" alt="NRI"></h1>
ロゴは見出しではないですね

2020-04-14 07:13 UTC, piasoratech commented on html-nri/index.html
> +    </div>
`header`、`main`、`footer`に含まれない要素はないので、どこかしらに含めましょう

2020-04-14 07:13 UTC, piasoratech commented on html-nri/index.html
> +            <h1>NRIのデジタルビジネス戦略</h1>
文章構造として見出しが後に来るのは一般的ではないのでタグを逆転させたほうが良いかと

2020-04-14 07:13 UTC, piasoratech commented on html-nri/index.html
> +        <article>
`article`を使うのであれば下の「NRIのデジタルビジネス戦略」からのほうが良いかと

2020-04-14 07:13 UTC, piasoratech commented on html-nri/index.html
> +                        <p>&lt;<a href="#">ビジネスモデルの特徴</a></p>
疑似要素使ってみましょう

2020-04-14 07:13 UTC, piasoratech commented on html-nri/index.html
> +                    <p>NRIの強み</p>
ここは見出しの扱いで良いかと

2020-04-14 07:13 UTC, piasoratech commented on html-nri/index.html
> +                    <!--&gt;">"はすべて::beforeで画像”＞”に差し替えます↓-->
それであればコードに&gt;を書いておく必要はありません

2020-04-14 07:13 UTC, piasoratech commented on html-nri/index.html
> +                        <p>経営方針</p>
この辺りも見出し扱いで良いかと

2020-04-14 07:13 UTC, piasoratech commented on html-nri/index.html
> +            <div class="copyright">
`div`を使用されている理由は何でしょう？

2020-04-14 07:13 UTC, piasoratech commented on html-nri/index.html
> +                    <div class="contents-link-first">
xxxx-firstなどのclass名もマジックナンバーを使っているのと大差ないので、使用するのをやめましょう。

2020-04-14 07:13 UTC, piasoratech commented on html-nri/index.html
> +    <footer>
`footer`は免責条項～のほうが良いと思います。

2020-04-14 07:28 UTC, Ryu-y-10 commented on html-nri/index.html
> +            <div class="copyright">
padding, margin など余白調整しやすくするためにdivで囲いました。

2020-04-15 03:06 UTC, piasoratech requested changes
指摘内容一部修正されていないので、もう一度確認をお願いします。

2020-04-15 06:39 UTC, piasoratech requested changes
コメントしたので確認をお願いします

2020-04-15 06:39 UTC, piasoratech commented on html-nri/index.html
> +                    &gt;<a href="#">前のページに戻る</a>
指摘しても直っていないというのはここのことを言っています。

> それであればコードに>を書いておく必要はありません

2020-04-15 06:39 UTC, piasoratech commented on html-nri/index.html
> +                    </ul>
わざわざ別のリストに分けている理由は何でしょうか？
３つずつ同じリストに入れても良いと思います。
また、ここを`strong`タグを使用して強調する必要はないと思います。
`strong`タグはその内容を文章として強調するのに適しているタグですが、太字にするなどの用途に使うものではありません。

2020-04-15 06:53 UTC, Ryu-y-10 commented on html-nri/index.html
> +                    </ul>
<ul>タグがブロック要素なのでコンテンツとコンテンツの余白を作るために別のリストにしてましたが見た目の調整は全てCSSで行いたいと思うので独立させているリストをまとめます。

2020-04-15 07:24 UTC, choimake approved these changes
お疲れ様でした。
LGTMです。

2020-04-16 03:24 UTC, merged